version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - ..:/workspace
      - ~/.gitconfig:/root/.gitconfig:ro
      - ~/.ssh/id_rsa:/root/.ssh/id_ed25519:ro
    command: sleep infinity
    ports:
      - 4000:4000
